repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=100']
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: double-quote-string-fixer
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/asottile/dead
    rev: v2.1.0
    hooks:
      - id: dead

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        args: [ --fix ]
        files: \.py$
      - id: ruff-format
        files: \.py$

# fix until there is an official hook to ty
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uvx ty check . --ignore unresolved-import
        language: python
